### ISSUE TITLE
Forcasting usign DSGE model

### ISSUE THREAD

**Issue by NicoGreggio** [gusamarante/dsgepy#5]
Hi everyone! 
I'm trying to forecast the observable variable using an estimated and calibrated standard DSGE using the Dsgepy library. Using some real data from FRED I calibrated the model but now i have some difficulty to forecast GDP, interest rates, exc. There are some examples or functions already in Python?

**Comment by gusamarante** [comment]
The DSGE object in this library currently does not have a forecasting, but I intend to add this functionality in the future. But the matrices that make up the model are available. So you can build your own forecast using those matrices and the Kalman filter. And if you do, please consider contributing on a Pull Request.

**Comment by NicoGreggio** [comment]
Thank you Gustavo, I think that given my level in coding with python I will wait. However, you have scheduled the implications in the next month? Or it's something that probably it will take years? 
Best.

**Comment by gusamarante** [comment]
This library is a pet project of mine. Is not under active development. But when I find myself bored during a rainy Sunday, I like to work on it. So, I cannot give any deadlines for implementation on any new feature. But I take notes of people's requests, and adding a native Kalman Filter is one the developments that I have at the top of my list.

**Comment by NicoGreggio** [comment]
An interesting way to pass the time 😅
However also since on DSGE models in python there is a lack of libraries, yours has some nice features.  
For your knowledge I am attaching a link to a notebook where the forecast feature is implemented: https://github.com/nflp/dsge_forecasting/blob/main/DSGE%20forecasting.ipynb
Thank you for your time Gustavo! 😊
