### ISSUE TITLE
Error using dsge.estimate() in: example_snkm.ipynb

### ISSUE THREAD

**Issue by NicoGreggio** [gusamarante/dsgepy#6]
Hi everyone!
I'm trying to reproduce the output in the Jupiter Notebook file "example_snkm.ipynb". I'm currently stuck in the following error when I'm running the dsge.estimate() function. I have not made any changes to the code. Thank you in advance: 

dsge.estimate(file_path='example_snkm.h5', nsim=2000, ck=0.2)
C:\Users\nicol\anaconda3\lib\site-packages\dsgepy\pycsminwel.py:438: RuntimeWarning: invalid value encountered in scalar subtract
  g0 = (fcn(x + tvecv) - f0) / delta
C:\Users\nicol\anaconda3\lib\site-packages\dsgepy\pycsminwel.py:438: RuntimeWarning: invalid value encountered in scalar subtract
  g0 = (fcn(x + tvecv) - f0) / delta
C:\Users\nicol\anaconda3\lib\site-packages\dsgepy\pycsminwel.py:438: RuntimeWarning: invalid value encountered in scalar subtract
  g0 = (fcn(x + tvecv) - f0) / delta
C:\Users\nicol\anaconda3\lib\site-packages\dsgepy\pycsminwel.py:438: RuntimeWarning: invalid value encountered in scalar subtract
  g0 = (fcn(x + tvecv) - f0) / delta
C:\Users\nicol\anaconda3\lib\site-packages\dsgepy\pycsminwel.py:438: RuntimeWarning: invalid value encountered in scalar subtract
  g0 = (fcn(x + tvecv) - f0) / delta
C:\Users\nicol\anaconda3\lib\site-packages\dsgepy\pycsminwel.py:438: RuntimeWarning: invalid value encountered in scalar subtract
  g0 = (fcn(x + tvecv) - f0) / delta
C:\Users\nicol\anaconda3\lib\site-packages\dsgepy\pycsminwel.py:438: RuntimeWarning: invalid value encountered in scalar subtract
  g0 = (fcn(x + tvecv) - f0) / delta
C:\Users\nicol\anaconda3\lib\site-packages\dsgepy\pycsminwel.py:438: RuntimeWarning: invalid value encountered in scalar subtract
  g0 = (fcn(x + tvecv) - f0) / delta
C:\Users\nicol\anaconda3\lib\site-packages\dsgepy\pycsminwel.py:438: RuntimeWarning: invalid value encountered in scalar subtract
  g0 = (fcn(x + tvecv) - f0) / delta
C:\Users\nicol\anaconda3\lib\site-packages\dsgepy\pycsminwel.py:347: RuntimeWarning: invalid value encountered in scalar subtract
  shrinkSignal = ((not badg) and (f0 - f < max(- theta * dfhat * lambda_, 0))) or (badg and (f0 - f < 0))
f at the beginning of iteration 1 is inf
C:\Users\nicol\anaconda3\lib\site-packages\dsgepy\pycsminwel.py:438: RuntimeWarning: invalid value encountered in scalar subtract
  g0 = (fcn(x + tvecv) - f0) / delta
C:\Users\nicol\anaconda3\lib\site-packages\dsgepy\pycsminwel.py:438: RuntimeWarning: invalid value encountered in scalar subtract
  g0 = (fcn(x + tvecv) - f0) / delta
C:\Users\nicol\anaconda3\lib\site-packages\dsgepy\pycsminwel.py:438: RuntimeWarning: invalid value encountered in scalar subtract
  g0 = (fcn(x + tvecv) - f0) / delta
C:\Users\nicol\anaconda3\lib\site-packages\dsgepy\pycsminwel.py:438: RuntimeWarning: invalid value encountered in scalar subtract
  g0 = (fcn(x + tvecv) - f0) / delta
C:\Users\nicol\anaconda3\lib\site-packages\dsgepy\pycsminwel.py:438: RuntimeWarning: invalid value encountered in scalar subtract
  g0 = (fcn(x + tvecv) - f0) / delta
C:\Users\nicol\anaconda3\lib\site-packages\dsgepy\pycsminwel.py:438: RuntimeWarning: invalid value encountered in scalar subtract
  g0 = (fcn(x + tvecv) - f0) / delta
C:\Users\nicol\anaconda3\lib\site-packages\dsgepy\pycsminwel.py:438: RuntimeWarning: invalid value encountered in scalar subtract
  g0 = (fcn(x + tvecv) - f0) / delta
C:\Users\nicol\anaconda3\lib\site-packages\dsgepy\pycsminwel.py:438: RuntimeWarning: invalid value encountered in scalar subtract
  g0 = (fcn(x + tvecv) - f0) / delta
C:\Users\nicol\anaconda3\lib\site-packages\dsgepy\pycsminwel.py:438: RuntimeWarning: invalid value encountered in scalar subtract
  g0 = (fcn(x + tvecv) - f0) / delta
C:\Users\nicol\anaconda3\lib\site-packages\dsgepy\pycsminwel.py:347: RuntimeWarning: invalid value encountered in scalar subtract
  shrinkSignal = ((not badg) and (f0 - f < max(- theta * dfhat * lambda_, 0))) or (badg and (f0 - f < 0))
Traceback (most recent call last):

  File "C:\Users\nicol\anaconda3\lib\site-packages\dsgepy\lineardsge.py", line 171, in estimate
    df_chains = pd.read_hdf(file_path, key='chains')

  File "C:\Users\nicol\anaconda3\lib\site-packages\pandas\io\pytables.py", line 414, in read_hdf
    raise FileNotFoundError(f"File {path_or_buf} does not exist")

FileNotFoundError: File example_snkm.h5 does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Users\nicol\AppData\Local\Temp\ipykernel_10112\3113586507.py", line 1, in <module>
    dsge.estimate(file_path='example_snkm.h5', nsim=2000, ck=0.2)

  File "C:\Users\nicol\anaconda3\lib\site-packages\dsgepy\lineardsge.py", line 187, in estimate
    _, theta_mode_irr, _, h, _, _, retcodeh = csminwel(fcn=obj_func, x0=theta_irr0, crit=1e-14, nit=100,

  File "C:\Users\nicol\anaconda3\lib\site-packages\dsgepy\pycsminwel.py", line 231, in csminwel
    nogh = gh.size == 0

AttributeError: 'NoneType' object has no attribute 'size'

**Comment by gusamarante** [comment]
If you made no changes to the code, it should run. Are you using the correct version of pykalman?

**Comment by NicoGreggio** [comment]
No changes. Installing using pip install pykalman, if I remember well version 0.95 using comda.

**Comment by gusamarante** [comment]
Then you have the wrong version. Read the installation instructions on the README.md file

**Comment by NicoGreggio** [comment]
I read the instructions but in conda terminal the instructions easy_install didn't work. Did you known the correct version of pykalman?

**Comment by gusamarante** [comment]
The "right" version of pykalman is the one that I modified. It is not a specific release of the original library.
